### PR TITLE
fix conn leakage issue

### PR DESCRIPTION
**Pull request by ccding**
fix conn leakage issue.

If a conn comes from outside, use it. Otherwise, create a new conn and close it at the end.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Looks good.

**Comment by AudriusButkevicius** [comment]
Yet there is another problem, if I change serverAddr, serverUDPAddr can never change.
It's fine to re-resolve the address on every discover, as it's fairly cheap, and helps dealing with DNS load balancers, etc.

**Comment by ccding** [comment]
How about it now?

**Comment by AudriusButkevicius** [comment]
LGTM

**Comment by AudriusButkevicius** [comment]
tyvm

**Pull request merged**
